theme: jekyll-theme-cayman
title: Diogo's Data Science Portfolio
# description: upbeat innovation!
description: emai: diogoncsa@gmail.com ; <a href="https://www.linkedin.com/in/diogoncsa/">Linkedin</a> ; <a href="https://bit.ly/2w1YR5c">CV</a>.
