theme: jekyll-theme-cayman

title: Diogo's Data Science Portfolio
description: upbeat innovation!

# desc: emai: diogoncsa@gmail.com ; <a href="https://www.linkedin.com/in/diogoncsa/">Linkedin</a> ; <a href="https://bit.ly/2w1YR5c">CV</a>.

email: diogoncsa@gmail.com
github_username:  perkier
linkedin_username: https://www.linkedin.com/in/diogoncsa/
